# Generated by Django 2.2.2 on 2019-07-11 18:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190710_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.generate_image_path),
        ),
    ]
