# Generated by Django 2.2.2 on 2019-07-11 19:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190711_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.generate_image_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
