# Generated by Django 2.2.2 on 2019-07-13 15:31

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190711_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.generate_image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog.Post')),
            ],
        ),
    ]
