# Generated by Django 2.2.2 on 2019-07-16 19:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190713_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(default='', editable=False, upload_to=blog.models.generate_image_path),
            preserve_default=False,
        ),
    ]
