# Generated by Django 2.2.2 on 2019-07-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_gallery_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='thumbnail',
        ),
    ]
